API adherence (#98)
* DeisaArray inherits DaskArray

* use new DeisaArray

* callback to register

* WindowSpec to Window

* register/register_callback support Window|str

* remove redefinition of queue_per_array

* add desctructor of bridge

* remove chunked and store_externally

* remove set,get,delete in scheduling actor

* remove unregister_callback

* fix close called twice

* remove_nb_chunks

* add deisa-core dep

* remove dtype

* nb_chunks_per_dim to global_shape

* make comm mandatory + remove gloo default

* remove system_metadata

* add default to get method

* init takes *args and **args

* bridge api done

* deepcopy arrays meta

* fix typo

fixes key error: -1

* fix exception handler

the logic was enforcing no raising even if user wants to raise. In this
way, if user wants to raise, the analytics will raise error.

* fix test to work with deisa.core validate_arrays_metadata

* comm derives from ICommunicator

* remove ray_start and max_sim_ahead args

* consistency with IDeisa

* reformat

* bridge.close returns None instead of int

* fix order to match API

* Window match deisa.core definition

* Hashable, Timestep to str, int

* fix test

* distributed scheduler option: config to env var

* minor fixes

* change event base synchro to Future for chunks_ready() and add_chunk() functions

---------

Co-authored-by: Hugo Strappazzon <hugo.strapp@hotmail.fr>